"""changes in notification time2

Revision ID: 2ecb416a685c
Revises: 363c84869069
Create Date: 2022-09-12 23:27:36.656450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecb416a685c'
down_revision = '363c84869069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('notification_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'notification_time')
    # ### end Alembic commands ###
