"""added active field to Student

Revision ID: 8499fa9f4c48
Revises: 2ecb416a685c
Create Date: 2022-11-02 22:54:49.175078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8499fa9f4c48'
down_revision = '2ecb416a685c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'active')
    # ### end Alembic commands ###
