"""added cid and notification_time

Revision ID: 85200094c8bd
Revises: 627a0b050b86
Create Date: 2022-09-12 23:01:14.266808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85200094c8bd'
down_revision = '627a0b050b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('cid', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('notification_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'notification_time')
    op.drop_column('student', 'cid')
    # ### end Alembic commands ###
