"""changes in lessons

Revision ID: 867ec4ab7b89
Revises: 808650a00694
Create Date: 2021-12-24 10:53:01.793417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867ec4ab7b89'
down_revision = '808650a00694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'lorder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('lorder', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
