"""changes in student.

Revision ID: c8dd48e894db
Revises: 69a6a5075872
Create Date: 2021-12-24 10:08:17.150266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dd48e894db'
down_revision = '69a6a5075872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('tid', sa.Integer(), nullable=True))
    op.drop_column('student', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('student', 'tid')
    # ### end Alembic commands ###
