"""changes in lessons

Revision ID: f640a2fff6c5
Revises: 867ec4ab7b89
Create Date: 2021-12-24 10:53:51.876145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f640a2fff6c5'
down_revision = '867ec4ab7b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'order')
    # ### end Alembic commands ###
